### PR TITLE
updated monaco-editor to latest

### PR DESCRIPTION
**Pull request by StefanRetief**
Upgrade for monaco editor. Fixed various issues:

- Fixed split-screen for "Problems" pane not rendering correctly
- Fixed transitions for opening & closing gallery/editor
- fixed minor styling issues
- Refactored markdown viewer into smaller components

**NOTE:** The sample editor component has been refactored into a react hook component. The editor has the ability to hook into a class component, but the work required is much too convoluted when hooks work fine.

I tested some samples and it appears that the files compile fine. Please do let me know if there are any samples that you test and run into a file not compiling as it should.

### CODE REVIEW

**Comment by williamkbentley** [comment]
I see an extra scroll bar on the right: 
image

**Comment by williamkbentley** [comment]
If the editor collapses itself, you cannot click the ">" button to re-expand it

**Review by williamkbentley — CHANGES_REQUESTED** [review]
See previous comments

**Comment by StefanRetief** [comment]
> I see an extra scroll bar on the right:

I'm not able to reproduce this, Could you check which element might be causing this?

**Comment by williamkbentley** [comment]
> > I see an extra scroll bar on the right:
> 
> I'm not able to reproduce this, Could you check which element might be causing this?

Not experiencing this anymore.

**Comment by StefanRetief** [comment]
> 
> 
> If the editor collapses itself, you cannot click the ">" button to re-expand it

Fixed this issue mostly. It's still running into issues, but they're very minor styling issues, which we I can fix in another PR.

**Review by williamkbentley — APPROVED** [review]
LGTM

**Pull request merged**
