### PR TITLE
update from the APIM team for Changed Elements API

### PR DESCRIPTION
**Pull request by Ellord207**

### CODE REVIEW

**Review by diegopinate — APPROVED** [review]
Looks good

**Comment by Josh-Schifter** [comment]
When I run this branch I'm getting 0 elements changed and 404s from the changeElements API.

**Comment by diegopinate** [comment]
> When I run this branch I'm getting 0 elements changed and 404s from the changeElements API.

The change to the API is not in PROD yet, it's only in QA, are you testing with QA?

**Comment by Josh-Schifter** [comment]
> are you testing with QA?

I was testing in PROD.  The PR didn't mention it would only work in QA.  Let's talk about deployments separately.

**Review by BaoTon — APPROVED** [review]
This is fine for staging.

**Pull request merged**
