### PR TITLE
Enable skybox for 3d  views.

### PR DESCRIPTION
**Pull request by pmconne**

### CODE REVIEW

**Comment by pmconne** [comment]
@Josh-Schifter because it's 2020 and we are *still* dealing with different line endings on unix and windows. You can change your settings to tell it to ignore whitespace changes.
image

**Comment by pmconne** [comment]
@Josh-Schifter Ugly brown is because you're in a top view in a non-geolocated file. Rotate the view to see why. If you prefer, I can override the default skybox settings.

**Comment by Josh-Schifter** [comment]
> @Josh-Schifter Ugly brown is because you're in a top view in a non-geolocated file. Rotate the view to see why. If you prefer, I can override the default skybox settings.

I don't think the ugly brown affected Retail Building (maybe I missed it).  I think we should do something because it looks pretty bad.  Either like you say, override the default skybox, or only to skybox for geolocated, or only do skybox for certain samples.

**Comment by pmconne** [comment]
Ugly brown is the default color you see when looking straight down in a top view of any non-geolocated model, including the retail building.
I changed that color. Is it less ugly now?

**Comment by Josh-Schifter** [comment]
> I changed that color. Is it less ugly now?

Seems like a good compromise.

**Pull request merged**
